// Google Places API のカテゴリを日本語に変換
export const typeToJapanese = (type: string): string => {
  const typeMap: { [key: string]: string } = {
    accounting: '会計事務所',
    airport: '空港',
    amusement_park: '遊園地',
    aquarium: '水族館',
    art_gallery: '美術館',
    atm: 'ATM',
    bakery: 'パン屋',
    bank: '銀行',
    bar: 'バー',
    beauty_salon: '美容室',
    bicycle_store: '自転車屋',
    book_store: '書店',
    bowling_alley: 'ボウリング場',
    bus_station: 'バス停',
    cafe: 'カフェ',
    campground: 'キャンプ場',
    car_dealer: '自動車ディーラー',
    car_rental: 'レンタカー屋',
    car_repair: '自動車修理, 板金屋',
    car_wash: '洗車',
    casino: 'カジノ',
    cemetery: '墓地',
    church: '教会',
    city_hall: '市役所',
    clothing_store: '洋服店',
    convenience_store: 'コンビニ',
    courthouse: '裁判所',
    dentist: '歯科',
    department_store: 'デパート',
    doctor: '医者',
    electrician: '電気事業者',
    electronics_store: '電器屋',
    embassy: '大使館',
    establishment: '飲食店や医療機関など',
    finance: '財務機関',
    fire_station: '消防署',
    florist: '花屋',
    food: '飲食店',
    funeral_home: '斎場',
    furniture_store: '家具屋',
    gas_station: 'ガソリンスタンド',
    general_contractor: 'ゼネコン',
    grocery_or_supermarket: '日用品店, スーパーマーケット',
    gym: 'スポーツジム',
    hair_care: '床屋',
    hardware_store: '工具店, ホームセンター',
    health: '主に医療機関',
    hindu_temple: 'ヒンドゥー寺院',
    home_goods_store: 'ホームセンター',
    hospital: '医療機関',
    insurance_agency: '保険代理店',
    jewelry_store: '宝石店',
    laundry: 'クリーニング店, コインランドリー',
    lawyer: '法律事務所',
    library: '図書館',
    liquor_store: '酒店',
    local_government_office: '地方公共団体',
    locksmith: '鍵屋',
    lodging: '宿泊施設',
    meal_delivery: '飲食店（出前形式）',
    meal_takeaway: '飲食店（テイクアウト形式）',
    mosque: 'モスク',
    movie_rental: 'ビデオレンタル屋',
    movie_theater: '映画館',
    moving_company: '運送屋, 引越し屋',
    museum: '博物館, ミュージアム',
    night_club: 'ナイトクラブ',
    painter: '塗装屋',
    park: '公園',
    parking: '駐車場',
    pet_store: 'ペット屋',
    pharmacy: '薬局',
    physiotherapist: '療法士',
    place_of_worship: '神社、寺',
    plumber: '配管工, 水道業者',
    police: '警察署, 交番',
    post_office: '郵便局',
    real_estate_agency: '不動産業者',
    restaurant: 'レストラン',
    roofing_contractor: '屋根屋',
    rv_park: 'RVパーク',
    school: '学校・塾',
    shoe_store: '靴屋',
    shopping_mall: '複合商業施設',
    spa: '温泉, 銭湯',
    stadium: 'スタジアム',
    storage: '倉庫',
    store: '店',
    subway_station: '地下鉄',
    synagogue: 'シナゴーグ',
    taxi_stand: 'タクシー乗り場',
    train_station: '鉄道駅',
    travel_agency: '旅行代理店',
    university: '大学',
    veterinary_care: '動物病院',
    zoo: '動物園',
    chinese_restaurant: '中華料理店',
    italian_restaurant: 'イタリアンレストラン',
    japanese_restaurant: '和食レストラン',
    french_restaurant: 'フレンチレストラン',
    indian_restaurant: 'インディアンレストラン',
    mexican_restaurant: 'メキシカンレストラン',
    sushi_restaurant: '寿司屋',
    ramen_restaurant: 'ラーメン屋',
    vegan_restaurant: 'ヴィーガンレストラン',
    vegetarian_restaurant: 'ベジタリアンレストラン',
    korean_restaurant: '韓国料理店',
    mediterranean_restaurant: '地中海料理店',
    mexican_grill: 'メキシカン・グリル',
    pizza_restaurant: 'ピザレストラン',
    hamburger_restaurant: 'ハンバーガー',
    sandwich_shop: 'サンドイッチ屋',
    american_restaurant: 'アメリカン',
    steak_house: 'ステーキハウス',
    dog_cafe: '犬カフェ',
    cat_cafe: '猫カフェ',
    wine_bar: 'ワインバー',
  };

  // マッチしたタイプがあればそれを返す
  if (typeMap[type]) {
    return typeMap[type];
  }

  // 未定義のタイプはそのまま返す
  return type || '未分類';
};
