import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ResponsiveHeader from "@/components/responsive/header/ResponsiveHeader";
import ResponsiveFooter from "@/components/responsive/footer/ResponsiveFooter";
import { Providers } from "./providers";
import { ListProvider } from "@/contexts/ListContext";
import { ListItemProvider } from "@/contexts/ListItemContext";
import "@/app/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ListProvider>
          <ListItemProvider>
            <Providers>
              <ResponsiveHeader />
              <main>{children}</main>
              <ResponsiveFooter />
            </Providers>
          </ListItemProvider>
        </ListProvider>
      </body>
    </html>
  );
}
